#include "sortableshape.h"

struct _SortableShapeObjectPrivate
{
  double r, g, b;
};

G_DEFINE_TYPE_WITH_PRIVATE (SortableShapeObject, sortable_shape_object, G_TYPE_OBJECT);

static void
sortable_shape_object_set_cairo_context (SortableShapeObject *self, cairo_t *cr)
{
  self->cr = cr;
}

static void
sortable_shape_object_class_init (SortableShapeObjectClass *klass)
{
  klass->draw = NULL;
  klass->set_cairo_context = sortable_shape_object_set_cairo_context;
}

static void
sortable_shape_object_init (SortableShapeObject *self)
{
  /* sortable_shape_object_get_instance_private() is generated by G_DEFINE_TYPE_WITH_PRIVATE()
   * above, and it's local to the current compilation unit.
   */
  /* SortableShapeObjectPrivate *priv = sortable_shape_object_get_instance_private (self); */

  /* priv->hsize = 42; */
}

static void
sortable_shape_object_set_color (SortableShapeObject *self, double r, double g,
    double b)
{
  self->priv->r = r;
  self->priv->g = g;
  self->priv->b = b;
}
