/* CairoSort
 * Copyright (C) <2014> Fabian Orccon <fabian.orccon@pucp.pe>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#include "sortableshape.h"

struct _SortableShapeObjectPrivate
{
  int dummy;
};

G_DEFINE_TYPE_WITH_PRIVATE (SortableShapeObject, sortable_shape_object, G_TYPE_OBJECT);

static void
sortable_shape_object_class_init (SortableShapeObjectClass *klass)
{
  klass->draw = NULL;
  klass->set_cairo_context = sortable_shape_object_set_cairo_context;
}

static void
sortable_shape_object_init (SortableShapeObject *self)
{
  /* sortable_shape_object_get_instance_private() is generated by G_DEFINE_TYPE_WITH_PRIVATE()
   * above, and it's local to the current compilation unit.
   */
  /* SortableShapeObjectPrivate *priv = sortable_shape_object_get_instance_private (self); */

  /* priv->hsize = 42; */
}

/* public */

void
sortable_shape_object_set_color (SortableShapeObject *self, double r, double g,
    double b)
{
  self->r = r;
  self->g = g;
  self->b = b;
}

void
sortable_shape_object_set_cairo_context (SortableShapeObject *self, cairo_t *cr)
{
  self->cr = cr;
}
